id: I8F475225
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:19:03+00:00'
last_modified: '2022-06-08T08:07:13.916987+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30429
  title: ཀུན་མཁྱེན་ངག་གི་དབང་པོའི་རང་རྣམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8367':
      image_group_id: I1KG22657
      title: ''
      total_pages: 320
      order: 1
      base_file: 8367.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
