id: P008234
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30429
  title: ཀུན་མཁྱེན་ངག་གི་དབང་པོའི་རང་རྣམ།
  author: ''
  volumes:
    6f60945308fa42df8c818d642f8ebef9:
      image_group_id: I1KG22657
      title: ''
      volume_number: 1
      total_pages: 320
      base_file: v001.txt
